ao_front_homepage:
    path:     /
    defaults: { _controller: "AoFrontBundle:Default:index" }

ao_front_search:
    path:     /search
    defaults: { _controller: "AoFrontBundle:Default:search" }

ao_front_categ_editGet:
    path:     /c/{uid}
    defaults: { _controller: "AoFrontBundle:Categ:editGet" }
    methods: [GET]
    requirements:
        uid: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"

ao_front_subcateg_editGet:
    path:     /sc/{uid}
    defaults: { _controller: "AoFrontBundle:SubCateg:editGet" }
    methods: [GET]
    requirements:
        uid: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"

ao_front_callfortender_editGet:
    path:     /ao/{uid}
    defaults: { _controller: "AoFrontBundle:Callfortender:editGet" }
    methods: [GET]
    requirements:
        uid: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"

ao_front_callfortender_pdf:
    path:     /aopdf/{uid}
    defaults: { _controller: "AoFrontBundle:Callfortender:pdf" }
    methods: [GET]
    requirements:
        uid: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"
