imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
#        main:
#            type: fingers_crossed
#            action_level: error
#            handler: nested
#        nested:
#            type: stream
#            path: '%kernel.logs_dir%/%kernel.environment%.log'
#            level: debug
        syslog_error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_error.log"
            level: error
            excluded_404s:
                - ^/
        syslog_info:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_info.log"
            level: info
        syslog_debug:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
