imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: en

framework:
    #esi: ~
    default_locale: '%locale%'
    
    translator:
        fallbacks:
            - '%locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: 'AcfResBundle::hinclude.html.twig'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        #handler_id: session.handler.native_file
        handler_id:  Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        name: "Acf"
        cookie_lifetime:      600
        #save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        gc_probability: 0
        gc_maxlifetime: 7200 #2592000 # optional, it is set to 30 days here
    fragments: { path: /_fragment }
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'SasedevCommonsBootstrapBundle::form.html.twig'
    globals:
        default_locale: "%locale%"
        sitename: "ACEF Expert"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
#        lessphp:
#            file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"
#            apply_to: \.less$
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                metadata_cache_driver: apcu
                query_cache_driver: 
                    type: memcache
                    host: localhost
                    port: 11211
                    instance_class: Memcache
                result_cache_driver:
                    type: memcache
                    host: localhost
                    port: 11211
                    instance_class: Memcache
                naming_strategy: doctrine.orm.naming_strategy.underscore
                second_level_cache:
                    enabled:              true

# doctrine mongodb odm
doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%mongodb_host%:%mongodb_port%"
#            options: {}
            options:
                username: "%mongodb_user%"
                password: "%mongodb_pass%"
                db: "%mongodb_auth%"
    default_database: "%mongodb_database%"
    auto_generate_proxy_classes:  true
    auto_generate_hydrator_classes:  true
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: memcache
                class: Doctrine\Common\Cache\MemcacheCache
                host: localhost
                port: 11211
                instance_class: Memcache
doctrine_cache:
    providers:
        vendor_filesystem_validation_cache:
            file_system:
                extension: cache
                directory: "%kernel.root_dir%/../var/cache/%kernel.environment%/doctrine/cache"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# sensio framework extra
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

# gedmo
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
#            tree: true
            timestampable: true
            sluggable: true
#            translatable: true

# jms_security_extra
#jms_security_extra:
#    secure_all_services: true

# JMS DI
#jms_di_extra:
#    locations:
#        all_bundles: false
#        directories: ["%kernel.root_dir%/../src/"]
#    automatic_controller_injections:
#        properties:
#            request: "@request"
#            router: "@router"
#        method_calls:
#            setRouter: ["@router"]

# knp_paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: SasedevCommonsBootstrapBundle::pagination.html.twig     # sliding pagination controls template
        sortable: SasedevCommonsBootstrapBundle::sortable_link.html.twig # sort link template


# liip imagine
#liip_imagine:
#    resolvers:
#        default:
#            web_path:
#              web_root: "%kernel.root_dir%/../web"
#              cache_prefix: /thumbs
#
#
#    loaders:
#        default:
#            filesystem:
#                data_root: "%kernel.root_dir%/../web/"
#
#    driver:               gd
#    cache:                default
#    data_loader:          default
#    controller_action:    liip_imagine.controller:filterAction
#
#    filter_sets:
#        cache: ~
#        thumbBanner:
#            filters:
#                relative_resize: { widen: 350 }
#        bigthumbBanner:
#            filters:
#                relative_resize: { widen: 600 }
#        thumbSitenew:
#            filters:
#                thumbnail: { size: [200, 200], mode: outbound }
#        thumbProd:
#            filters:
#                thumbnail: { size: [220, 220], mode: outbound }
#                upscale:
#                    min: [220, 220]
#                    max: [220, 220]
#                relative_resize: { widen: 220 }
#        thumbProductpic:
#            filters:
#                relative_resize: { widen: 300 }
#        bigthumbProductpic:
#            filters:
#                relative_resize: { widen: 400 }
#        thumbPics:
#            filters:
#                relative_resize: { heighten: 400 }
#        bigthumbQuotation:
#            filters:
#                relative_resize: { widen: 600 }

# LuneticsLocaleBundle
#lunetics_locale:
#    strict_mode: true # defaults to false
#    allowed_locales:
#        - en
#        - fr
#        - ar
#        - de
#    guessing_order:
#        - query
#        - cookie
#        - session
#        - browser
#        - router
#    cookie:
#        set_on_change: true
#    switcher:
#        template: AcfFrontBundle::setlocale.html.twig
#        show_current_locale: true

# lexik_translation
#lexik_translation:
#    fallback_locale: fr      # (required) default locale to use
#    managed_locales: [en, fr]    # (required) locales that the bundle have to manage
#
#    base_layout:     "LexikTranslationBundle::layout.html.twig" # layout used with the translation edition template
#    use_yml_tree:    false    # if "true" we will print a nice tree in the yml source files. It is a little slower.
#    grid_input_type: textarea     # define field type used in the grid (text|textarea)
#    grid_toggle_similar: true  # if "true", on the grid if a locale colunm is shown/hidden then similar locales columns will be shown/hidden too.
#                                    # so if the col "en" is shown/hidden all "en_XX" cols will be shown/hidden too. Not in the reverse order ("en_XX" clicked, no impact on "en")
#    storage:
#        type: orm                    # where to store translations: "orm", "mongodb" or "propel"
#        object_manager: something    # The name of the entity / document manager which uses different connection (see: http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html)
                                     # When using propel, this can be used to specify the propel connection name
#    resources_registration:
#        type:                 all     # resources type to register: "all", "files" or "database"
#        managed_locales_only: true    # will only load resources for managed locales
