acf_security:
    resource: "@AcfSecurityBundle/Resources/config/routing.yml"
    prefix:   /

acf_res:
    resource: "@AcfResBundle/Resources/config/routing.yml"
    prefix:   /

acf_front:
    resource: "@AcfFrontBundle/Resources/config/routing.yml"
    prefix:   /

acf_admin:
    resource: "@AcfAdminBundle/Resources/config/routing.yml"
    prefix:   /ACEF-Admin

acf_client:
    resource: "@AcfClientBundle/Resources/config/routing.yml"
    prefix:   /ACEF-Cloud

acf_info:
    resource: "@AcfInfoBundle/Resources/config/routing.yml"
    prefix:   /ACEF-Info
    
acf_payroll:
    resource: "@AcfPayrollBundle/Resources/config/routing.yml"
    prefix:   /ACEF-Payroll

acf_liasse:
    resource: "@AcfLiasseBundle/Resources/config/routing.yml"
    prefix:   /ACEF-Liasse

acf_tools:
    resource: "@AcfToolsBundle/Resources/config/routing.yml"
    prefix:   /ACEF-Tools

ao_admin:
    resource: "@AoAdminBundle/Resources/config/routing.yml"
    prefix:   /AO-Admin

ao_front:
    resource: "@AoFrontBundle/Resources/config/routing.yml"
    prefix:   /AO-Front


