# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    default_locale:            "%locale%"
    adapter_cache_dir:         "%kernel.root_dir%/cache/%kernel.environment%/filesystem"
    adapter_tmp_files:         "%kernel.root_dir%/../var/TempFiles"
    adapter_files:             "%kernel.root_dir%/../var/Files"
    mail_from:                 "system@acf-expert.tn"
    mail_from_name:            "acf-expert.tn"
    mailtos:
        - { name: 'Faiez Fakhfakh', email: 'faiez.fakhfakh@acf-expert.tn' }

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.i18n:
       class: Twig_Extensions_Extension_I18n
       tags:
           - { name: twig.extension }

    twig.extension.array:
       class: Twig_Extensions_Extension_Array
       tags:
           - { name: twig.extension }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

    validator.mapping.cache.doctrine:
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments:
            - '@doctrine_cache.providers.vendor_filesystem_validation_cache'
    # ...
    mongo_client:
        class: MongoClient
        # if using a username and password
        arguments:
            - 'mongodb://%mongodb_host%:%mongodb_port%'
            - { username: %mongodb_user%, password: %mongodb_pass%, db: %mongodb_auth%}
    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo_client', '%mongo.session.options%']
        

