Acf\DataBundle\Entity\Address:
    type: entity
    table: acf_company_addresses
    repositoryClass: Acf\DataBundle\Repository\AddressRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        streetNum:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: strnum
        address:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        address2:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        town:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        zipCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: zipcode
        country:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        phone:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        mobile:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        fax:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        email:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        otherInfos:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: others
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: addresses
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
