Acf\DataBundle\Entity\Agenda:
    type: entity
    table: acf_agenda_events
    repositoryClass: Acf\DataBundle\Repository\AgendaRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        dtStart:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: evt_start
        dtEnd:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: evt_end
        title:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: evt_title
        comment:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: evt_comments
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        user:
            targetEntity: Acf\DataBundle\Entity\User
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: events
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        users:
            targetEntity: Acf\DataBundle\Entity\User
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: sharedEvents
            joinTable:
                name: acf_agenda_shares
                schema: null
                joinColumns:
                    -
                        name: evt_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
