Acf\DataBundle\Entity\BulletinInfoContent:
    type: entity
    table: acf_bi_contents
    repositoryClass: Acf\DataBundle\Repository\BulletinInfoContentRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: bc_title
        content:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_content
        theme:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_theme
        jort:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_jort
        txtNum:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_txtnum
        artTxt:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_arttxt
        dtTxt:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_dttxt
        artCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_artcode
        companyType:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_stetype
        dtApplication:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bc_dtapp
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        bulletinInfoTitle:
            targetEntity: Acf\DataBundle\Entity\BulletinInfoTitle
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: contents
            joinColumns:
                bt_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
