Acf\DataBundle\Entity\Company:
    type: entity
    table: acf_companies
    repositoryClass: Acf\DataBundle\Repository\CompanyRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        ref:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        corporateName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: corporate_name
        tribunal:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        fisc:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        cnss:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        cnssBureau:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bureaucnss
        physicaltype:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        cin:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        passport:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        commercialRegister:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: commercial_register
        commercialRegisterBureau:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: bureaurc
        customsCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: customs_code
        actionvn:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 10
        streetNum:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: strnum
        address:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        address2:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        town:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        zipCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: zipcode
        country:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        phone:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        mobile:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        fax:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        email:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        otherInfos:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: others
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        type:
            targetEntity: Acf\DataBundle\Entity\CompanyType
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: companies
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        stocks:
            targetEntity: Acf\DataBundle\Entity\Stock
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                year: ASC
        phones:
            targetEntity: Acf\DataBundle\Entity\Phone
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        addresses:
            targetEntity: Acf\DataBundle\Entity\Address
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        companyFrames:
            targetEntity: Acf\DataBundle\Entity\CompanyFrame
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                lastName: ASC
                firstName: ASC
        companyLabels:
            targetEntity: Acf\DataBundle\Entity\CompanyLabel
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                name: ASC
        shareholders:
            targetEntity: Acf\DataBundle\Entity\Shareholder
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                name: ASC
        pilots:
            targetEntity: Acf\DataBundle\Entity\Pilot
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                mission: ASC
        companyNatures:
            targetEntity: Acf\DataBundle\Entity\CompanyNature
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        relations:
            targetEntity: Acf\DataBundle\Entity\Relation
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        companyUsers:
            targetEntity: Acf\DataBundle\Entity\CompanyUser
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
        companyAdmins:
            targetEntity: Acf\DataBundle\Entity\CompanyAdmin
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
        accounts:
            targetEntity: Acf\DataBundle\Entity\Account
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        withholdings:
            targetEntity: Acf\DataBundle\Entity\Withholding
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        monthlyBalances:
            targetEntity: Acf\DataBundle\Entity\MonthlyBalance
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                year: ASC
                month: ASC
        payes:
            targetEntity: Acf\DataBundle\Entity\MPaye
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                year: ASC
                month: ASC
        invoices:
            targetEntity: Acf\DataBundle\Entity\OnlineInvoice
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: DESC
        docgroups:
            targetEntity: Acf\DataBundle\Entity\Docgroup
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docgroupcomptables:
            targetEntity: Acf\DataBundle\Entity\Docgroupcomptable
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docgroupfiscals:
            targetEntity: Acf\DataBundle\Entity\Docgroupfiscal
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docgrouppersos:
            targetEntity: Acf\DataBundle\Entity\Docgroupperso
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docgroupsysts:
            targetEntity: Acf\DataBundle\Entity\Docgroupsyst
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docgroupbanks:
            targetEntity: Acf\DataBundle\Entity\Docgroupbank
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docgroupaudits:
            targetEntity: Acf\DataBundle\Entity\Docgroupaudit
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
        docs:
            targetEntity: Acf\DataBundle\Entity\Doc
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: company
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: DESC
    manyToMany:
        sectors:
            targetEntity: Acf\DataBundle\Entity\Sector
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: companies
            joinTable:
                name: acf_company_sectors
                schema: null
                joinColumns:
                    -
                        name: company_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: sector_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        users:
            targetEntity: Acf\DataBundle\Entity\User
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: companies
            joinTable:
                name: acf_company_users
                schema: null
                joinColumns:
                    -
                        name: company_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        admins:
            targetEntity: Acf\DataBundle\Entity\User
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: admCompanies
            joinTable:
                name: acf_company_admins
                schema: null
                joinColumns:
                    -
                        name: company_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
