Acf\DataBundle\Entity\ConstantStr:
    type: entity
    table: acf_constant_strs
    repositoryClass: Acf\DataBundle\Repository\ConstantStrRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        value:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: val
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
