Acf\DataBundle\Entity\Doc:
    type: entity
    table: acf_company_docs
    repositoryClass: Acf\DataBundle\Repository\DocRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        fileName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filename
        size:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filesize
        mimeType:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filemimetype
        md5:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filemd5
        originalName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: fileoname
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: filedesc
        nbrDownloads:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filedls
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        groups:
            targetEntity: Acf\DataBundle\Entity\Docgroup
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_group_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        groupcomptables:
            targetEntity: Acf\DataBundle\Entity\Docgroupcomptable
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_groupcomptable_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        groupfiscals:
            targetEntity: Acf\DataBundle\Entity\Docgroupfiscal
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_groupfiscal_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        grouppersos:
            targetEntity: Acf\DataBundle\Entity\Docgroupperso
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_groupperso_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        groupsysts:
            targetEntity: Acf\DataBundle\Entity\Docgroupsyst
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_groupsyst_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        groupbanks:
            targetEntity: Acf\DataBundle\Entity\Docgroupbank
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_groupbank_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        groupaudits:
            targetEntity: Acf\DataBundle\Entity\Docgroupaudit
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_groupaudit_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        accounts:
            targetEntity: Acf\DataBundle\Entity\Account
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_account_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: account_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        relations:
            targetEntity: Acf\DataBundle\Entity\Relation
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_relation_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: relation_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        monthlyBalances:
            targetEntity: Acf\DataBundle\Entity\MonthlyBalance
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_mbalance_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: mbalance_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        transactions:
            targetEntity: Acf\DataBundle\Entity\Transaction
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_transaction_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: transaction_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        mpayes:
            targetEntity: Acf\DataBundle\Entity\MPaye
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinTable:
                name: acf_mpaye_docs
                schema: null
                joinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: mpaye_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
