Acf\DataBundle\Entity\Docgroupbank:
    type: entity
    table: acf_company_docgroupbanks
    repositoryClass: Acf\DataBundle\Repository\DocgroupbankRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        pageUrlFull:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: pageurl_full
            gedmo:
                slug:
                  separator: "_"
                  style: camel
                  fields:
                      - label
                  handlers:
                      'Gedmo\Sluggable\Handler\TreeSlugHandler':
                          parentRelationField: parent
                          separator: /
        otherInfos:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: others
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docgroupbanks
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
        parent:
            targetEntity: Acf\DataBundle\Entity\Docgroupbank
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: childs
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        childs:
            targetEntity: Acf\DataBundle\Entity\Docgroupbank
            cascade:
                - persist
            fetch: LAZY
            mappedBy: parent
            inversedBy: null
            orphanRemoval: false
            orderBy:
                label: ASC
    manyToMany:
        docs:
            targetEntity: Acf\DataBundle\Entity\Doc
            cascade:
                - persist
            fetch: LAZY
            mappedBy: groupbanks
            inversedBy: null
            joinTable:
                name: acf_groupbank_docs
                schema: null
                joinColumns:
                    -
                        name: group_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
