Acf\DataBundle\Entity\FeedRead:
    type: entity
    table: acf_feedreads
    repositoryClass: Acf\DataBundle\Repository\FeedReadRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        url:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        nbrDays:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: nbrdays
        nbrItems:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: nbritems
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
