Acf\DataBundle\Entity\GoodLink:
    type: entity
    table: acf_goodlinks
    repositoryClass: Acf\DataBundle\Repository\GoodLinkRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        url:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        nbrClicks:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: nbrclicks
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
