Acf\DataBundle\Entity\Job:
    type: entity
    table: acf_jobs
    repositoryClass: Acf\DataBundle\Repository\JobRepository
    id:
        id:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        companyFrames:
            targetEntity: Acf\DataBundle\Entity\CompanyFrame
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: job
            inversedBy: null
            orphanRemoval: false
            orderBy:
                lastName: ASC
                firstName: ASC
    lifecycleCallbacks: {  }
