Acf\DataBundle\Entity\MBSale:
    type: entity
    table: mbsale
    repositoryClass: Acf\DataBundle\Repository\MBSaleRepository
    fields:
        ref:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        year:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        month:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        count:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: cnt
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: monthlyBalances
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        transactions:
            targetEntity: Acf\DataBundle\Entity\Transaction
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: monthlyBalance
            inversedBy: null
            orphanRemoval: false
            orderBy:
                number: ASC
    manyToMany:
        docs:
            targetEntity: Acf\DataBundle\Entity\Doc
            cascade:
                - persist
            fetch: LAZY
            mappedBy: monthlyBalances
            inversedBy: null
            joinTable:
                name: acf_mbalance_docs
                schema: null
                joinColumns:
                    -
                        name: mbalance_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
