Acf\DataBundle\Entity\MSalary:
    type: entity
    table: acf_msalaries
    repositoryClass: Acf\DataBundle\Repository\MSalaryRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        matricule:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: ref
        nom:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        prenom:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        actif:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: active
        fonction:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        regime:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        dtStartContrat:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: dtstartcontrat
        dtEndContrat:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: dtendcontrat
        departement:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        categorie:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        echelon:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        cin:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        cnss:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        birthday:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        adresse:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        tel:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        email:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: mail
        banque:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        rib:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        familyChef:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: chefdefamille
        familySituation:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: situationfamiliale
        handicap:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: enfanthandicap
        childWoBourse:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: enfantsansbourse
        nbrDaysWork:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nbrjwork
        nbrDaysAbs:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nbrjabsence
        nbrDaysFerry:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nbrjconge
        nbrH075Sup:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nbrh075sup
        nbrH100Sup:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nbrh100sup
        nbrDSup:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nbrjsup
        remboursement:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        buysFromCompany:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: achatste
        salaryAdvance:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: avancesalaire
        salaryBrut:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: salairebrut
        salaryNet:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: salairenet
        advantageNature:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: avantagenature
        ticketResto:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: ticketresto
        ticketCadeau:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: ticketcadeau
        lifeAssurance:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: assurancevie
        ceaAccount:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: comptecea
        others:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: remarques
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        paye:
            targetEntity: Acf\DataBundle\Entity\MPaye
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: salaries
            joinColumns:
                mpaye_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
