Acf\DataBundle\Entity\OnlineInvoiceDocument:
    type: entity
    table: acf_online_invoice_docs
    repositoryClass: Acf\DataBundle\Repository\OnlineInvoiceDocumentRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        fileName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filename
        size:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filesize
        mimeType:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filemimetype
        md5:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: filemd5
        originalName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: fileoname
        visible:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        invoice:
            targetEntity: Acf\DataBundle\Entity\OnlineInvoice
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: docs
            joinColumns:
                inv_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
