Acf\DataBundle\Entity\OnlineInvoiceProduct:
    type: entity
    table: acf_online_invoice_elements
    repositoryClass: Acf\DataBundle\Repository\OnlineInvoiceProductRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: prd_label
        price:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: prd_price_ht
        vat:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: prd_vat
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        invoice:
            targetEntity: Acf\DataBundle\Entity\OnlineInvoice
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            joinColumns:
                inv_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
