Acf\DataBundle\Entity\OnlineInvoice:
    type: entity
    table: acf_online_invoices
    repositoryClass: Acf\DataBundle\Repository\OnlineInvoiceRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        ref:
            type: text
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
        val:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        orderTo:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: orderto
        paymentType:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: payment_type
        status:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: payment_status
        renew:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: autorenew
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        user:
            targetEntity: Acf\DataBundle\Entity\User
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: orders
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: invoices
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        order:
            targetEntity: Acf\DataBundle\Entity\OnlineOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: invoice
            joinColumns:
                ord_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        products:
            targetEntity: Acf\DataBundle\Entity\OnlineInvoiceProduct
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: invoice
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
        taxes:
            targetEntity: Acf\DataBundle\Entity\OnlineInvoiceTaxe
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: invoice
            inversedBy: null
            orphanRemoval: false
            orderBy:
                priority: ASC
        docs:
            targetEntity: Acf\DataBundle\Entity\OnlineInvoiceDocument
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: invoice
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
    lifecycleCallbacks: {  }
