Acf\DataBundle\Entity\Phone:
    type: entity
    table: acf_company_phones
    repositoryClass: Acf\DataBundle\Repository\PhoneRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        phone:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        contact:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: phones
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
