Acf\DataBundle\Entity\Pilot:
    type: entity
    table: acf_company_pilots
    repositoryClass: Acf\DataBundle\Repository\PilotRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        ref:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        mission:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        natureMission:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nat_mission
        prestataire:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        recetteFinance:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: recfin
        pinAnce:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: pinance
        expirationAnce:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: expirationance
        mpImpots:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: mpimpots
        idCnss:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: idcnss
        mpCnss:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: mdpcnss
        nomCac:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nom_cac
        dureeMandat:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: duree_mandat
        numMandat:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: num_mandat
        rapportCac:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: rapport_cac
        declEmpl:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: decl_empl
        isDur:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: is_dur
        pvCa:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: pv_ca
        rapportGerance:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: rapport_gerance
        pvAgo:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: pv_ago
        pvAge:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: pv_age
        livresCotes:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: livres_cotes
        honTeorAnn:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: hon_theo_ann
        modeFact:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: mode_fact
        nonFactMont:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: non_fact_m
        nonFactDesc:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nom_fact_d
        nonEncMont:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nom_enc_m
        nonEncDesc:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nom_enc_d
        commentQuit:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: comment_quit
        mqQuitImpots:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: mq_quit_impots
        mqQuitCnss:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: mq_quit_cnss
        comments:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: commentaires
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: pilots
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
