Acf\DataBundle\Entity\Relation:
    type: entity
    table: acf_company_relations
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: relationtype
        type: string
        length: null
        columnDefinition: null
        fieldName: relationtype
    discriminatorMap:
        1: Acf\DataBundle\Entity\Customer
        2: Acf\DataBundle\Entity\Supplier
    repositoryClass: Acf\DataBundle\Repository\RelationRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        number:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: numb
        fisc:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        physicaltype:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        cin:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        passport:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        commercialRegister:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: commercial_register
        streetNum:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: strnum
        address:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        address2:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        town:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        zipCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: zipcode
        country:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        phone:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        mobile:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        fax:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        email:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        otherInfos:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: others
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: relations
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        sectors:
            targetEntity: Acf\DataBundle\Entity\Sector
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: relations
            joinTable:
                name: acf_relation_sectors
                schema: null
                joinColumns:
                    -
                        name: relation_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: sector_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        docs:
            targetEntity: Acf\DataBundle\Entity\Doc
            cascade:
                - persist
            fetch: LAZY
            mappedBy: relations
            inversedBy: null
            joinTable:
                name: acf_relation_docs
                schema: null
                joinColumns:
                    -
                        name: relation_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: doc_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    oneToMany:
        transactions:
            targetEntity: Acf\DataBundle\Entity\Transaction
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: relation
            inversedBy: null
            orphanRemoval: false
            orderBy:
                number: ASC
    lifecycleCallbacks: {  }
