Acf\DataBundle\Entity\Role:
    type: entity
    table: acf_roles
    repositoryClass: Acf\DataBundle\Repository\RoleRepository
    id:
        id:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            scale: 0
            length: 250
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        parents:
            targetEntity: Acf\DataBundle\Entity\Role
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: childs
            joinTable:
                name: acf_role_parents
                schema: null
                joinColumns:
                    -
                        name: child
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: parent
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy:
                name: ASC
        childs:
            targetEntity: Acf\DataBundle\Entity\Role
            cascade: {  }
            fetch: LAZY
            mappedBy: parents
            inversedBy: null
            joinTable:
                name: acf_role_parents
                schema: null
                joinColumns:
                    -
                        name: parent
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: child
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy:
                name: ASC
        users:
            targetEntity: Acf\DataBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: userRoles
            inversedBy: null
            joinTable:
                name: acf_users_roles
                schema: null
                joinColumns:
                    -
                        name: role_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
