Acf\DataBundle\Entity\Sale:
    type: entity
    repositoryClass: Acf\DataBundle\Repository\SaleRepository
    oneToMany:
        secondaryVats:
            targetEntity: Acf\DataBundle\Entity\SecondaryVat
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: sale
            inversedBy: null
            orphanRemoval: false
            orderBy:
                vatInfo: ASC
    lifecycleCallbacks: {  }
