Acf\DataBundle\Entity\SecondaryVat:
    type: entity
    table: acf_transaction_vats
    repositoryClass: Acf\DataBundle\Repository\SecondaryVatRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        vatInfo:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: vatinfo
        vat:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 10
        balanceNet:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 10
            column: balance_net
        balanceTtc:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 10
            column: balance_ttc
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        sale:
            targetEntity: Acf\DataBundle\Entity\Sale
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: secondaryVats
            joinColumns:
                transaction_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
