Acf\DataBundle\Entity\Sector:
    type: entity
    table: acf_cmp_sectors
    repositoryClass: Acf\DataBundle\Repository\SectorRepository
    id:
        id:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        label:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        companies:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: sectors
            inversedBy: null
            joinTable:
                name: acf_company_sectors
                schema: null
                joinColumns:
                    -
                        name: sector_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: company_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        relations:
            targetEntity: Acf\DataBundle\Entity\Relation
            cascade:
                - persist
            fetch: LAZY
            mappedBy: sectors
            inversedBy: null
            joinTable:
                name: acf_relation_sectors
                schema: null
                joinColumns:
                    -
                        name: sector_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: relation_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
