Acf\DataBundle\Entity\Shareholder:
    type: entity
    table: acf_company_shareholders
    repositoryClass: Acf\DataBundle\Repository\ShareholderRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        cin:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        quality:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        address:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        trades:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: shareholders
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
