Acf\DataBundle\Entity\Stock:
    type: entity
    table: acf_company_stocks
    repositoryClass: Acf\DataBundle\Repository\StockRepository
    id:
        id:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: UUID
    fields:
        year:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        value:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: val
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        company:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: stocks
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
