Acf\DataBundle\Entity\Trace:
    type: entity
    table: acf_traces
    repositoryClass: Acf\DataBundle\Repository\TraceRepository
    id:
        id:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        msg:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        actionType:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: action_type
        actionEntity:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: action_entity
        actionId:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: action_id
        actionEntity2:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: action_entity2
        actionId2:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: action_id2
        actionEntity3:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: action_entity3
        actionId3:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: action_id3
        actionEntity4:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: action_entity4
        actionId4:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: action_id4
        companyId:
            type: guid
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: company_id
        userId:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: user_id
        userFullname:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: user_fullname
        userType:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: user_type
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
