Acf\DataBundle\Entity\User:
    type: entity
    table: acf_users
    repositoryClass: Acf\DataBundle\Repository\UserRepository
    id:
        id:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        username:
            type: text
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
        email:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        salt:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        clearPassword:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: clearpassword
        password:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: passwd
        recoveryCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: recoverycode
        recoveryExpiration:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: recoveryexpiration
        lockout:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        logins:
            type: bigint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        lastLogin:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: lastlogin
        lastActivity:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: lastactivity
        lastName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: lastname
        firstName:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: firstname
        sexe:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        birthday:
            type: date
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        streetNum:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: strnum
        address:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        address2:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        town:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        zipCode:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: zipcode
        country:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        phone:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        mobile:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        avatar:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        dtCrea:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: created_at
        dtUpdate:
            type: datetimetz
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        preferedLang:
            targetEntity: Acf\DataBundle\Entity\Lang
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: users
            joinColumns:
                lang_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        userRoles:
            targetEntity: Acf\DataBundle\Entity\Role
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: users
            joinTable:
                name: acf_users_roles
                schema: null
                joinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: role_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        companies:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade: {  }
            fetch: LAZY
            mappedBy: users
            inversedBy: null
            joinTable:
                name: acf_company_users
                schema: null
                joinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: company_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        admCompanies:
            targetEntity: Acf\DataBundle\Entity\Company
            cascade:
                - persist
            fetch: LAZY
            mappedBy: admins
            inversedBy: null
            joinTable:
                name: acf_company_admins
                schema: null
                joinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: company_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        sharedEvents:
            targetEntity: Acf\DataBundle\Entity\Agenda
            cascade:
                - persist
            fetch: LAZY
            mappedBy: users
            inversedBy: null
            joinTable:
                name: acf_agenda_shares
                schema: null
                joinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: evt_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        sharedNotifs:
            targetEntity: Acf\DataBundle\Entity\Notification
            cascade:
                - persist
            fetch: LAZY
            mappedBy: users
            inversedBy: null
            joinTable:
                name: acf_notif_shares
                schema: null
                joinColumns:
                    -
                        name: user_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: notif_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    oneToMany:
        companyUsers:
            targetEntity: Acf\DataBundle\Entity\CompanyUser
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
        companyAdmins:
            targetEntity: Acf\DataBundle\Entity\CompanyAdmin
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
        events:
            targetEntity: Acf\DataBundle\Entity\Agenda
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtStart: ASC
        notifs:
            targetEntity: Acf\DataBundle\Entity\Notification
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
        orders:
            targetEntity: Acf\DataBundle\Entity\OnlineOrder
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy:
                dtCrea: ASC
    lifecycleCallbacks: {  }
