_info_homepage:
    path:     /
    defaults: { _controller: "AcfInfoBundle:Default:index" }

_info_bulletinInfo_editGet:
    path:     /bulletinInfo/{uid}
    defaults: { _controller: "AcfInfoBundle:Default:editGet" }
    methods: [GET]
    requirements:
        uid: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"


_info_biDoc_download:
    path:     /biDoc/download/{uid}
    defaults: { _controller: "AcfInfoBundle:BiDoc:download" }
    requirements:
        uid: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"

