services:
    AcfDataBundle.TraceListener:
        class:  Acf\DataBundle\Listener\TraceListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }
