<?php
namespace Acf\DataBundle\Repository;

use Acf\DataBundle\Entity\AoSubCateg;
use Doctrine\ORM\EntityRepository;

/**
 * AoAdvertisementRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class AoAdvertisementRepository extends EntityRepository
{

    /**
     * All count
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function count()
    {
        $qb = $this->createQueryBuilder('sc')->select('count(sc)');
        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * Get Query for All Entities
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('sc')->orderBy('sc.title', 'ASC');
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAll()
    {
        return $this->getAllQuery()->execute();
    }

    /**
     * All count
     *
     * @param AoSubCateg $categ
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function countByGroup(AoSubCateg $group)
    {
        $qb = $this->createQueryBuilder('sc')
            ->select('count(ad)')
            ->join('ad.group', 'sc')
            ->where('sc.id = :id')
            ->setParameter('id', $group->getId());
        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * Get Query for All Entities
     *
     * @param AoSubCateg $group
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllByGroupQuery(AoSubCateg $group)
    {
        $qb = $this->createQueryBuilder('ad')
            ->join('ad.group', 'sc')
            ->where('sc.id = :id')
            ->orderBy('ad.dtCrea', 'DESC')
            ->setParameter('id', $group->getId());
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param AoSubCateg $group
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAllByGroup(AoSubCateg $group)
    {
        return $this->getAllByGroupQuery($group)->execute();
    }
}

