<?php
namespace Acf\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Acf\DataBundle\Entity\Company;

/**
 * CompanyLabelRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class CompanyLabelRepository extends EntityRepository
{

    /**
     * All count
     *
     * @param Company $c
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function countByCompany(Company $c)
    {
        $qb = $this->createQueryBuilder('cl')->select('count(cl)')->join('cl.company', 'c')->where('c.id = :id')->setParameter('id', $c->getId());
        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * Get Query for All Entities
     *
     * @param Company $c
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllByCompanyQuery(Company $c)
    {
        $qb = $this->createQueryBuilder('cl')->join('cl.company', 'c')->where('c.id = :id')->orderBy('cl.name', 'ASC')->setParameter('id', $c->getId());
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param Company $c
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAllByCompany(Company $c)
    {
        return $this->getAllByCompanyQuery($c)->execute();
    }
}
