<?php
namespace Acf\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Acf\DataBundle\Entity\Company;
use Acf\DataBundle\Entity\Docgroupsyst;

/**
 * DocgroupRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class DocgroupsystRepository extends EntityRepository
{

    /**
     * Get Query for All Entities
     *
     * @param null|Company $c
     *
     * @return \Doctrine\ORM\Query
     */
    public function getRootsQuery(Company $c = null)
    {
        if (null == $c) {
            $qb = $this->createQueryBuilder('d')
                ->where('d.parent is NULL')
                ->orderBy('d.label', 'ASC');
        } else {
            $qb = $this->createQueryBuilder('d')
                ->join('d.company', 'c')
                ->where('d.parent is NULL')
                ->andWhere('c.id = :id')
                ->orderBy('d.label', 'ASC')
                ->setParameter('id', $c->getId());
        }
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param null|Company $c
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getRoots(Company $c = null)
    {
        return $this->getRootsQuery($c)->execute();
    }

    /**
     * Get Query for All Entities
     *
     * @param null|Company $c
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllQuery(Company $c = null)
    {
        if (null == $c) {
            $qb = $this->createQueryBuilder('d')->orderBy('d.pageUrlFull', 'ASC');
        } else {
            $qb = $this->createQueryBuilder('d')
                ->join('d.company', 'c')
                ->where('c.id = :id')
                ->orderBy('d.pageUrlFull', 'ASC')
                ->setParameter('id', $c->getId());
        }
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param null|Company $c
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAll(Company $c = null)
    {
        return $this->getAllQuery($c)->execute();
    }

    /**
     * Get Query for All Entities
     *
     * @param Docgroupsyst $dg
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllChildsQuery(Docgroupsyst $dg)
    {
        $c = $dg->getCompany();
        $qb = $this->createQueryBuilder('d')
            ->join('d.company', 'c')
            ->where('c.id = :cid')
            ->andWhere('d.pageUrlFull LIKE :url')
            ->andWhere('d.id != :did')
            ->orderBy('d.pageUrlFull', 'ASC')
            ->setParameter('cid', $c->getId())
            ->setParameter('url', $dg->getPageUrlFull() . '%')
            ->setParameter('did', $dg->getId());
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param Docgroupsyst $dg
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAllChilds(Docgroupsyst $dg)
    {
        return $this->getAllChildsQuery($dg)->execute();
    }
}
