<?php
namespace Acf\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Acf\DataBundle\Entity\LiasseFolder;

/**
 * LiasseDocRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class LiasseDocRepository extends EntityRepository
{

    /**
     * Get Query for All Entities
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('l')->orderBy('l.dtCrea', 'DESC');
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAll()
    {
        return $this->getAllQuery()->execute();
    }

    /**
     * Get Query for All Entities
     *
     * @param LiasseFolder $f
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllByFolderQuery(LiasseFolder $f)
    {
        $qb = $this->createQueryBuilder('l')
            ->join('l.folder', 'f')
            ->where('f.id = :id')
            ->orderBy('l.title', 'ASC')
            ->setParameter('id', $f->getId());
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param LiasseFolder $f
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAllByFolder(LiasseFolder $f)
    {
        return $this->getAllByFolderQuery($f)->execute();
    }
}
