<?php

namespace Acf\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonthlyBalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyBalanceRepository extends EntityRepository
{
}
