<?php
namespace Acf\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Acf\DataBundle\Entity\Company;

/**
 * PhoneRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{

    /**
     * Get Query for All Entities
     *
     * @param Company $c
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAllByCompanyQuery(Company $c)
    {
        $qb = $this->createQueryBuilder('p')
            ->join('p.company', 'c')
            ->where('c.id = :id')
            ->orderBy('p.label', 'ASC')
            ->setParameter('id', $c->getId());
        $query = $qb->getQuery();

        return $query;
    }

    /**
     * Get All Entities
     *
     * @param Company $c
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAllByCompany(Company $c)
    {
        return $this->getAllByCompanyQuery($c)->execute();
    }
}
